In [1]:
import torch

# Choosing devices


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"

# Working with tensor

In [7]:
my_tensor = torch.tensor (([[3,4,5],[2,3,4]]), dtype = torch.float
            ,device = device, requires_grad = True)

In [8]:
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[3., 4., 5.],
        [2., 3., 4.]], requires_grad=True)
torch.float32
cpu
torch.Size([2, 3])
True


# Other common initialization methods

In [9]:
x = torch.empty(size = (3,3))
print(x)

tensor([[-1.6339e+10,  4.5625e-41,  2.8026e-45],
        [ 0.0000e+00,  2.5816e-02,  3.0771e-41],
        [-1.6339e+10,  4.5625e-41,  1.4013e-45]])


In [10]:
x = torch.zeros(3,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
x = torch.rand(3,3)
print(x)

tensor([[0.8805, 0.2499, 0.9307],
        [0.4338, 0.6099, 0.6402],
        [0.9752, 0.1932, 0.1853]])


In [12]:
x = torch.eye(5,5) #Returns a 2-D tensor with ones on the diagonal and zeros elsewhere
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [14]:
x = torch.arange(start=0,end=5,step=1) # Returns 1-D tensor
print(x)

tensor([0, 1, 2, 3, 4])


In [16]:
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [24]:
x = torch.empty(size=(1,5)).normal_(mean=0,std=1) #Returns 2-D tensor with mean=0 and std=1 
print(x)
print(x.dim()) # to find the dimension of the tensor

tensor([[ 1.5867, -0.5360, -0.3342, -1.5922, -1.4569]])
2


In [25]:
x = torch.empty(size=(1,5)).uniform_(0,1) # Returns 2-D tensor from 0-1
print(x)
print(x.dim())

tensor([[0.8244, 0.5427, 0.2747, 0.9517, 0.9998]])
2


In [26]:
x = torch.diag(torch.ones(3)) #Returns 2-D tensor with the diagonal 1
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# Initializing and converting tensors into different types

In [30]:
tensor = torch.arange(4)
print(tensor)

tensor([0, 1, 2, 3])


In [31]:
print(tensor.dtype)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.double())

torch.int64
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.], dtype=torch.float64)


# Numpy array to tensor conversion and vice versa

In [33]:
import numpy as np
np_array = np.ones((5,5))
print(np_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [34]:
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


In [ ]:
numpy_array_back = tensor.numpy(tensor)
print(nump)