# Tensor Math and Comparision Operation

In [1]:
import torch

In [3]:
x = torch.tensor([1,2,3])
y = torch.tensor([7,8,9])

# Addition

In [4]:
z = torch.add(x,y)
print(z)

tensor([ 8, 10, 12])


In [5]:
z = x + y
print(z)

tensor([ 8, 10, 12])


# Subtraction

In [6]:
z = x-y
print(z)

tensor([-6, -6, -6])


# Division ( element wise division)

In [7]:
z = torch.true_divide(x,y)
print(z)

tensor([0.1429, 0.2500, 0.3333])


# Exponentiation

In [8]:
z = x.pow(2)
print(z)


tensor([1, 4, 9])


# Inplace operations 

In [10]:
t = torch.zeros(3)
t.add_(x)
t += x  #t=t+x
print(t)

tensor([2., 4., 6.])


# Single Comparision

In [11]:
z = x>0
print (z)

tensor([True, True, True])


# Matrix Multiplication

In [18]:
x1 = torch.rand((2,5))
# print(x1)
x2 = torch.rand((5,4))
# print(x2)
x3 = torch.mm(x1,x2)
print(x3)

tensor([[1.4358, 1.3279, 1.7352, 1.8768],
        [0.7212, 1.3235, 1.3533, 1.3182]])


# Matrix Exponentiation

In [19]:
matrix_exp = torch.rand(5,5)
print(matrix_exp)
print(matrix_exp.matrix_power(3))


tensor([[0.1086, 0.8254, 0.0907, 0.3425, 0.0934],
        [0.7261, 0.7899, 0.8464, 0.7229, 0.0189],
        [0.6092, 0.1171, 0.5518, 0.7659, 0.9648],
        [0.7376, 0.4428, 0.7283, 0.1384, 0.0955],
        [0.0524, 0.7676, 0.3708, 0.0481, 0.7404]])
tensor([[2.0121, 2.1549, 2.1146, 1.9351, 1.3421],
        [3.6534, 4.3658, 4.0210, 3.3740, 2.7415],
        [2.9328, 3.8884, 3.4746, 2.8745, 2.5660],
        [2.4526, 3.0060, 2.7855, 2.1299, 1.8065],
        [2.4487, 2.9745, 2.8083, 2.2871, 2.0069]])


# Element Wise matrix multiplication

In [20]:
z = x*y
print(z)


tensor([ 7, 16, 27])


# Dot Product

In [21]:
z = torch.dot(x,y)
print(z)


tensor(50)


# Batch matrix multiplicaiton

In [22]:
batch = 32
n =10
m = 20
p =30

tensor1 = torch.rand(batch,n,m)
tensor2 = torch.rand(batch,m,p)

out_bmm = torch.bmm(tensor1,tensor2)
print(out_bmm)

tensor([[[6.6042, 7.2259, 4.8116,  ..., 6.9335, 5.3164, 4.8397],
         [7.3137, 7.2447, 6.3860,  ..., 7.1917, 6.3964, 5.9104],
         [5.0181, 5.6200, 4.0689,  ..., 5.3122, 3.8328, 3.8208],
         ...,
         [5.3247, 6.9737, 4.4168,  ..., 5.5474, 5.1130, 4.6704],
         [5.6383, 6.3610, 4.2503,  ..., 5.7390, 4.4092, 4.2215],
         [7.1515, 8.8144, 5.3308,  ..., 7.5979, 6.3226, 6.0068]],

        [[3.9703, 5.5151, 4.3698,  ..., 5.1806, 6.0258, 3.3284],
         [4.8865, 5.3797, 4.5759,  ..., 5.5212, 6.6854, 4.6043],
         [4.2409, 5.6889, 4.2670,  ..., 4.5512, 6.2271, 3.7184],
         ...,
         [5.9605, 6.3328, 5.0815,  ..., 5.6400, 7.5370, 4.2454],
         [5.7520, 5.1173, 4.5635,  ..., 5.1418, 6.5609, 3.9333],
         [4.6420, 5.7545, 4.8745,  ..., 6.1971, 5.9858, 3.5646]],

        [[4.6963, 4.9081, 4.6227,  ..., 5.0408, 4.5399, 5.6337],
         [5.0439, 4.9147, 3.9046,  ..., 4.5644, 5.4252, 5.1532],
         [5.5598, 4.8949, 4.2542,  ..., 5.9544, 5.7971, 6.

# Broadcasting Example

In [25]:
x1 = torch.rand((5,5))
print(x1)
x2 = torch.rand((1,5))
print(x2)
z = x1-x2 
print(z)

tensor([[0.8216, 0.8936, 0.8867, 0.4860, 0.7860],
        [0.2696, 0.4360, 0.0041, 0.2071, 0.2486],
        [0.7227, 0.9788, 0.7047, 0.9737, 0.2014],
        [0.1496, 0.7671, 0.4813, 0.2486, 0.1263],
        [0.8676, 0.0525, 0.6724, 0.0983, 0.1565]])
tensor([[0.3052, 0.4981, 0.8994, 0.7619, 0.8351]])
tensor([[ 0.5164,  0.3955, -0.0127, -0.2759, -0.0491],
        [-0.0355, -0.0622, -0.8953, -0.5548, -0.5865],
        [ 0.4176,  0.4807, -0.1947,  0.2117, -0.6338],
        [-0.1556,  0.2690, -0.4181, -0.5134, -0.7088],
        [ 0.5624, -0.4457, -0.2270, -0.6637, -0.6787]])
