# Tensor Indexing

In [2]:
import torch

batch_size = 10
features = 25
x = torch.rand((batch_size,features))
print(x)


tensor([[0.7018, 0.9645, 0.8287, 0.3934, 0.8088, 0.4162, 0.0602, 0.7012, 0.8931,
         0.0113, 0.7554, 0.0822, 0.9344, 0.4410, 0.3756, 0.1685, 0.0469, 0.0399,
         0.7201, 0.7876, 0.6903, 0.7990, 0.6754, 0.8061, 0.2370],
        [0.1229, 0.9515, 0.6432, 0.2256, 0.8148, 0.6619, 0.0295, 0.9752, 0.4956,
         0.3947, 0.8354, 0.2532, 0.1234, 0.7376, 0.1052, 0.2425, 0.8024, 0.3134,
         0.7071, 0.9081, 0.2126, 0.5742, 0.0128, 0.6751, 0.0495],
        [0.8946, 0.7254, 0.6463, 0.2092, 0.5480, 0.6857, 0.0052, 0.4459, 0.2176,
         0.6828, 0.3498, 0.3557, 0.4613, 0.1838, 0.4753, 0.8213, 0.1969, 0.6311,
         0.4128, 0.3717, 0.9108, 0.4270, 0.3075, 0.9937, 0.0631],
        [0.0484, 0.6066, 0.5425, 0.1122, 0.8362, 0.5178, 0.3101, 0.2113, 0.3984,
         0.4771, 0.0149, 0.2401, 0.3673, 0.9467, 0.8321, 0.5261, 0.4509, 0.9745,
         0.9612, 0.2386, 0.4277, 0.3290, 0.1398, 0.6732, 0.1601],
        [0.8995, 0.4233, 0.8007, 0.8225, 0.1371, 0.9864, 0.1094, 0.7093, 0.5073,
       

# Finding the features of first batch

In [5]:
print(x[0])
print(x[0].shape)

tensor([0.7018, 0.9645, 0.8287, 0.3934, 0.8088, 0.4162, 0.0602, 0.7012, 0.8931,
        0.0113, 0.7554, 0.0822, 0.9344, 0.4410, 0.3756, 0.1685, 0.0469, 0.0399,
        0.7201, 0.7876, 0.6903, 0.7990, 0.6754, 0.8061, 0.2370])
torch.Size([25])


# Getting first features from every batches 

In [6]:
print(x[:,0])
print(x[:,0].shape)

tensor([0.7018, 0.1229, 0.8946, 0.0484, 0.8995, 0.0065, 0.1675, 0.5648, 0.3596,
        0.2674])
torch.Size([10])


# Getting first 10 features from the third batch

In [7]:
print(x[2,0:10])

tensor([0.8946, 0.7254, 0.6463, 0.2092, 0.5480, 0.6857, 0.0052, 0.4459, 0.2176,
        0.6828])


# Fancy Indexing

In [8]:
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


# More advanced indexing

In [10]:
x = torch.arange(10)
print(x[(x <2) | (x >8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


# Useful operation

In [11]:
print (torch.where(x>5, x, x*2))
#printing unique values from the list
print(torch.tensor([0,0,1,1,2,2,3,4]).unique())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])


# Finding the dimension

In [ ]:
print(x.ndimension)
print9