# Tensor reshaping

In [1]:
import torch

x = torch.arange(9)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [3]:
# view and reshape are quite similar
# x_3x3 = x.view(3,3)
x_3x3 = x.reshape(3,3)
print(x_3x3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


# Transpose

In [5]:
y = x_3x3.t()
print(y)
print(y.reshape(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [7]:
x1 = torch.rand((2,5))
print(x1)
x2 = torch.rand((2,5))
print(x2)
# concatenates the given sequence of seq tensors in the given dimension
print(torch.cat((x1,x2),dim=0))
print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2),dim=1))
print(torch.cat((x1,x2),dim=1).shape)

tensor([[0.1319, 0.0867, 0.5919, 0.8516, 0.9666],
        [0.6912, 0.3022, 0.0957, 0.6012, 0.4135]])
tensor([[0.5707, 0.3442, 0.5932, 0.1327, 0.3291],
        [0.2213, 0.1019, 0.1571, 0.9507, 0.0191]])
tensor([[0.1319, 0.0867, 0.5919, 0.8516, 0.9666],
        [0.6912, 0.3022, 0.0957, 0.6012, 0.4135],
        [0.5707, 0.3442, 0.5932, 0.1327, 0.3291],
        [0.2213, 0.1019, 0.1571, 0.9507, 0.0191]])
torch.Size([4, 5])
tensor([[0.1319, 0.0867, 0.5919, 0.8516, 0.9666, 0.5707, 0.3442, 0.5932, 0.1327,
         0.3291],
        [0.6912, 0.3022, 0.0957, 0.6012, 0.4135, 0.2213, 0.1019, 0.1571, 0.9507,
         0.0191]])
torch.Size([2, 10])
